### ISSUE TITLE
Missing SSL on Mac OSX

### ISSUE THREAD

**Issue by naqvis** [oprypin/install-crystal#3]
Using this github action to install crystal on latest OSX is yielding 
`ld: library not found for -lssl (this usually means you need to install the development package for libssl)` error, when crystal code depending on openssl.

Operating System
```
  Mac OS X
  10.15.7
  19H15
  ```

**Comment by oprypin** [comment]
Thanks for the report.

The fix is released in https://github.com/oprypin/install-crystal/releases/tag/v1.3.0
